import test from 'node:test'
import assert from 'node:assert/strict'
import fs from 'node:fs'
import path from 'node:path'
import {fileURLToPath} from 'node:url'
import {
  estimateGlobalTranslation,compensateSubjectMotionV3,PersistentSurfaceMap,PersistentIdentityManager,
  PersistentHandDogRelations,PersistentObjectInteractionEvidence,TemporalPostureClassifier,DeepVideoDebugRecorder,parseVisionStructuredPayload,validateStructuredVision,
  normalizeVisionStructuredPayload,orderedSemanticFrameTimestamps,fitAspectPreservingDimensions,conservativeVisionFallback,generateCandidateIntervals,mergePettingEpisodes,reconcileV3Events,selectDeepV3StoryEvents,evaluateRegressionV001
} from '../public/deep-video-v3.js'
import {analyseDeepWindow,hasNarrativeSchemaContamination,sanitizeFinalNarrative} from '../studio.mjs'

const here=path.dirname(fileURLToPath(import.meta.url))
const fixture=JSON.parse(fs.readFileSync(path.resolve(here,'../../tests/fixtures/regression-video-001.expected.json'),'utf8'))
const schemaEchoRegression='In the video, [ { "events": [ { "actor_ref": "subject_1", "action": "petting|lying_down|standing_up|sitting_down|jumping_off|jumping_on|approaching_person|rear_up|tail_wagging|sniffing|object_presented|mouth_contact|picking_up|holding|carrying|playing|tugging|dropping|dog_dog_interaction|person_dog_interaction|resting|walking|running|rolling|other"'
const jpeg='data:image/jpeg;base64,AA=='
const sequenceFrames=[{timestamp:3,image:jpeg,width:640,height:360},{timestamp:1,image:jpeg,width:640,height:360},{timestamp:2,image:jpeg,width:640,height:360}]

function texture(width=80,height=80){const data=new Uint8Array(width*height);for(let y=0;y<height;y++)for(let x=0;x<width;x++)data[y*width+x]=(x*17+y*29+(x*y)%97)%256;return data}
function shifted(input,dx,dy,width=80,height=80){const output=new Uint8Array(input.length);for(let y=0;y<height;y++)for(let x=0;x<width;x++){const px=x-dx,py=y-dy;output[y*width+x]=px>=0&&px<width&&py>=0&&py<height?input[py*width+px]:0}return output}
const descriptor=(hue=0)=>({histogram:Array.from({length:20},(_,index)=>index===hue?1:0),shape:[.4,.3,.2,.2]})

test('camera pan is recovered from multiple static background features',()=>{const previous=texture(),current=shifted(previous,4,-3),motion=estimateGlobalTranslation(previous,current,{width:80,height:80,maxShift:7});assert.ok(Math.abs(motion.dx-.05)<.014);assert.ok(Math.abs(motion.dy+.0375)<.014);assert.ok(motion.inliers>100);assert.ok(motion.confidence>.25)})
test('static dog with moving camera has near-zero residual motion',()=>{const residual=compensateSubjectMotionV3({dx:.05,dy:-.02},{dx:.05,dy:-.02,confidence:.8});assert.ok(residual.magnitude<1e-6)})
test('moving dog with static camera retains subject motion',()=>{const residual=compensateSubjectMotionV3({dx:.06,dy:0},{dx:0,dy:0,confidence:.8});assert.ok(Math.abs(residual.dx-.06)<1e-6)})
test('camera and dog moving together preserve only residual movement',()=>{const residual=compensateSubjectMotionV3({dx:.08,dy:.01},{dx:.05,dy:.01,confidence:.8});assert.ok(Math.abs(residual.dx-.03)<1e-6)})
test('semantic frame timestamps stay ordered across the full interval',()=>{assert.deepEqual(orderedSemanticFrameTimestamps({start:92.6,end:101.5},6),[92.6,94.38,96.16,97.94,99.72,101.5])})
test('semantic frame dimensions preserve source aspect ratio',()=>{const landscape=fitAspectPreservingDimensions(1920,1080,640),portrait=fitAspectPreservingDimensions(1080,1920,640);assert.deepEqual(landscape,{width:640,height:360});assert.deepEqual(portrait,{width:360,height:640});assert.equal(landscape.width/landscape.height,16/9)})

test('alternating couch bed couch chair bed labels stay one generic surface with no transition',()=>{const map=new PersistentSurfaceMap({confirmFrames:3,relationFrames:2}),dog={subject_id:'subject_1',box:[.25,.28,.55,.62]},transitions=[],labels=['couch','bed','couch','chair','bed'];for(let frame=0;frame<40;frame++){map.updateDetections([{label:labels[frame%labels.length],score:.8,box:[.18,.2,.72,.72]}],frame*.2);const transition=map.updateRelation(dog,frame*.2);if(transition)transitions.push(transition)}const surfaces=map.snapshot();assert.equal(surfaces.length,1);assert.equal(surfaces[0].stable_type,'furniture_surface');assert.equal(transitions.length,0);assert.equal(JSON.stringify(transitions).includes('bed'),false)})
test('leaving and returning to persistent furniture creates only cooled geometric support events',()=>{const map=new PersistentSurfaceMap({confirmFrames:2,relationFrames:2,cooldownSeconds:1}),on={subject_id:'subject_1',box:[.25,.28,.55,.62]},floor={subject_id:'subject_1',box:[.76,.45,.96,.9]};for(let frame=0;frame<4;frame++){map.updateDetections([{label:'couch',score:.9,box:[.18,.2,.72,.72]}],frame*.2);map.updateRelation(on,frame*.2)}let off=null;for(let frame=4;frame<7;frame++)off=map.updateRelation(floor,frame*.2)||off;assert.equal(off.action,'jumping_off');let back=null;for(let frame=13;frame<16;frame++)back=map.updateRelation(on,frame*.2)||back;assert.equal(back.action,'jumping_on');assert.equal(off.to.surface,'floor');assert.equal(back.from.surface,'floor')})
test('dog already on furniture at startup does not create an initial jumping_on',()=>{const map=new PersistentSurfaceMap({confirmFrames:2,relationFrames:2,relationSeconds:.35,cooldownSeconds:0}),dog={subject_id:'subject_1',box:[.25,.28,.55,.62]},events=[];for(const time of [0,.2,.4]){const event=map.updateRelation(dog,time);if(event)events.push(event)}for(const time of [.6,.8,1,1.2]){map.updateDetections([{label:'couch',score:.9,box:[.18,.2,.72,.72]}],time);const event=map.updateRelation(dog,time);if(event)events.push(event)}assert.equal(events.some(event=>event.action==='jumping_on'),false)})
test('confirmed floor followed by furniture still creates jumping_on',()=>{const map=new PersistentSurfaceMap({confirmFrames:2,relationFrames:2,relationSeconds:.35,cooldownSeconds:0}),floor={subject_id:'subject_1',box:[.76,.45,.96,.9]},on={subject_id:'subject_1',box:[.25,.28,.55,.62]},events=[];for(const time of [0,.2,.4,.6,.8,1,1.2,1.4,1.6,1.8,2,2.2]){map.updateDetections([{label:'couch',score:.9,box:[.18,.2,.72,.72]}],time);const event=map.updateRelation(floor,time);if(event)events.push(event)}for(const time of [2.4,2.6,2.8]){map.updateDetections([{label:'couch',score:.9,box:[.18,.2,.72,.72]}],time);const event=map.updateRelation(on,time);if(event)events.push(event)}assert.equal(events.filter(event=>event.action==='jumping_on').length,1)})
test('moving between furniture entities never creates a semantic scene change',()=>{const map=new PersistentSurfaceMap({confirmFrames:2,relationFrames:2,cooldownSeconds:0}),left={subject_id:'subject_1',box:[.12,.25,.34,.62]},right={subject_id:'subject_1',box:[.66,.25,.88,.62]},detections=[{label:'couch',score:.9,box:[.06,.18,.42,.72]},{label:'chair',score:.9,box:[.58,.18,.95,.72]}],events=[];for(let frame=0;frame<4;frame++){map.updateDetections(detections,frame*.2);map.updateRelation(left,frame*.2)}for(let frame=4;frame<8;frame++){map.updateDetections(detections,frame*.2);const event=map.updateRelation(right,frame*.2);if(event)events.push(event)}assert.equal(map.entities.size,2);assert.deepEqual(events,[])})

test('lost dog with a new temporary track revives the persistent subject',()=>{const manager=new PersistentIdentityManager({newSubjectFrames:2,newSubjectSeconds:10,matchThreshold:.4}),box=[.2,.2,.5,.7];manager.update([{label:'dog',track_id:'track_1',box,descriptor:descriptor(2)}],0);const created=manager.update([{label:'dog',track_id:'track_1',box,descriptor:descriptor(2)}],.2)[0];assert.equal(created.subject_id,'subject_1');const revived=manager.update([{label:'dog',track_id:'track_9',box:[.22,.2,.52,.7],descriptor:descriptor(2)}],2)[0];assert.equal(revived.subject_id,'subject_1');assert.equal(revived.identity_decision,'revived');assert.equal(manager.subjects.size,1)})

test('temporal posture classifier implements stable sitting',()=>{const points=Array.from({length:17},()=>({x:0,y:0,score:0}));points[3]={x:.4,y:.3,score:.9};points[4]={x:.6,y:.65,score:.9};for(const index of [7,10])points[index]={x:.42,y:.85,score:.85};for(const index of [13,16])points[index]={x:.62,y:.72,score:.85};const classifier=new TemporalPostureClassifier({confirmFrames:2,minConfidence:.5});classifier.update('subject_1',points,0);const stable=classifier.update('subject_1',points,.3);assert.equal(stable.stable,'sitting')})

test('malformed structured response is explicit and useful fallback is retained',()=>{const invalid=validateStructuredVision('The dog is tail wagging and is being petted.',{interval:{start:2,end:5},knownSubjects:['subject_1']});assert.equal(invalid.valid,false);assert.ok(invalid.errors.includes('invalid_json_or_schema'));const fallback=conservativeVisionFallback('The dog is tail wagging and is being petted.',{interval:{start:2,end:5},actor:'subject_1'});assert.deepEqual(new Set(fallback.map(event=>event.action)),new Set(['tail_wagging','petting']))})
test('exact Regression 001 schema echo produces zero fallback or semantic events',async()=>{assert.equal(conservativeVisionFallback(schemaEchoRegression,{interval:{start:0,end:3},actor:'subject_1'}).length,0);const calls=[];const result=await analyseDeepWindow({language:'en',interval:{start:0,end:3},sequence:{frames:sequenceFrames},knownSubjects:['subject_1']},async messages=>{calls.push(messages);return schemaEchoRegression});const prompt=calls[0][0].content.find(item=>item.type==='text'&&/Return one JSON object/.test(item.text)).text;assert.equal(calls.length,1);assert.doesNotMatch(prompt,/petting\s*\|\s*lying_down/);assert.doesNotMatch(prompt,/"action"\s*:\s*"petting"|repeatedly strokes subject_1/i);assert.doesNotMatch(prompt,/surface_before|evidence|object_label/);assert.equal(result.events.length,0);assert.ok(result.decisions.some(item=>item.reason==='schema_echo_or_template'))})
test('a copied JSON action template is rejected before event construction',()=>{const copied=JSON.stringify({events:[{actor_ref:'subject_1',action:'petting|lying_down|standing_up|holding|playing',start:0,end:1,confidence:.9,evidence:['short observable reason']}],context:{environment:'unknown'}}),validated=validateStructuredVision(copied,{interval:{start:0,end:2},knownSubjects:['subject_1']});assert.equal(validated.valid,false);assert.equal(validated.events.length,0);assert.ok(validated.errors.includes('schema_echo_or_template'))})
test('valid structured response produces persistent-reference events',()=>{const parsed=validateStructuredVision(JSON.stringify({events:[{actor_ref:'subject_1',action:'petting',target_ref:'person_1',start:3,end:5,confidence:.86,evidence:['hand repeatedly contacts the dog']}],context:{environment:'indoor',scene:'home'}}),{interval:{start:2,end:6},knownSubjects:['subject_1','person_1']});assert.equal(parsed.valid,true);assert.equal(parsed.events.length,1);assert.equal(parsed.events[0].actor,'subject_1')})
test('Vision parser accepts wrapped, array, single-object and repairable almost-JSON forms',()=>{const interval={start:4,end:7},knownSubjects=['subject_1','person_1'],cases=[
  'Here is the result: {"events":[{"actor_ref":"subject_1","action":"petting","confidence":0.8}]} Thanks.',
  '[{"actor_ref":"subject_1","action":"playing","confidence":0.75}]',
  '{"actor_ref":"subject_1","action":"tail-wagging","confidence":0.72}',
  '```json\n{"events":[{"actor":"subject_1","action":"petting","detail":"A hand strokes the dog.","confidence":0.8},],}\n```',
  "{'events':[{'subject':'subject_1','action':'playing','target':'person_1','confidence':0.7}]}",
  '“actor”: “subject_1”, “action”: “petting”'
];for(const value of cases){const wrapped=value.startsWith('“')?`{${value}}`:value,parsed=validateStructuredVision(wrapped,{interval,knownSubjects});assert.equal(parsed.valid,true,value);assert.equal(parsed.events.length,1,value);assert.equal(parsed.events[0].start,4);assert.equal(parsed.events[0].end,7);assert.ok(parsed.events[0].description.length>8)}})
test('normal action gets conservative default confidence but high-specificity action does not',()=>{const normal=validateStructuredVision({actor:'subject_1',action:'playing'},{interval:{start:1,end:2},knownSubjects:['subject_1']}),specific=validateStructuredVision({actor:'subject_1',action:'biting'},{interval:{start:1,end:2},knownSubjects:['subject_1']});assert.equal(normal.events[0].confidence,.68);assert.equal(specific.events.length,0)})
test('nested explicit VisionPsy event shape normalizes without inventing fields',()=>{const nested={actor_ref:{actor:{name:'subject_1'},action:{action:'petting'},target_ref:{target:{name:'person_1'},confidence:.82}}},normalized=normalizeVisionStructuredPayload(nested),validated=validateStructuredVision(nested,{interval:{start:4,end:7},knownSubjects:['subject_1','person_1']});assert.equal(normalized.applied,true);assert.equal(normalized.payload.events[0].actor_ref,'subject_1');assert.equal(normalized.payload.events[0].action,'petting');assert.equal(normalized.payload.events[0].target_ref,'person_1');assert.equal(normalized.payload.events[0].confidence,.82);assert.equal(validated.valid,true);assert.equal(validated.normalization_applied,true);assert.equal(validated.events[0].actor,'subject_1')})
test('malformed VisionPsy JSON is retried once and repaired',async()=>{const replies=['not valid json but the dog is being petted',JSON.stringify({events:[{actor_ref:'subject_1',action:'petting',target_ref:'person_1',start:3,end:5,confidence:.86,evidence:['repeated hand contact']}],context:{environment:'indoor',scene:'home'}})],calls=[];const result=await analyseDeepWindow({language:'en',interval:{start:2,end:6},sequence:{image:'data:image/jpeg;base64,AA=='},knownSubjects:['subject_1','person_1']},async messages=>{calls.push(messages);return replies.shift()});assert.equal(calls.length,2);assert.equal(result.metrics.repaired_responses,1);assert.equal(result.events.length,1);assert.ok(result.decisions.some(item=>item.status==='accepted'))})
test('valid structured empty response increments empty metrics only',async()=>{const result=await analyseDeepWindow({language:'en',interval:{id:'empty',start:2,end:4,reasons:['coverage'],subjects:['subject_1'],salience:.35},sequence:{image:'data:image/jpeg;base64,AA=='},knownSubjects:['subject_1']},async()=>'{"events":[]}');assert.equal(result.metrics.valid_structured_responses,1);assert.equal(result.metrics.valid_structured_empty,1);assert.equal(result.metrics.valid_structured_with_events,0);assert.equal(result.metrics.structured_events_created,0)})
test('valid structured semantic response increments with-events metrics',async()=>{const calls=[],result=await analyseDeepWindow({language:'en',interval:{id:'semantic',start:2,end:4},sequence:{image:'data:image/jpeg;base64,AA=='},knownSubjects:['subject_1']},async messages=>{calls.push(messages);return '{"events":[{"actor_ref":"subject_1","action":"holding","confidence":0.86,"description":"The dog holds an object in its mouth."}]}' });assert.equal(result.metrics.valid_structured_responses,1);assert.equal(result.metrics.valid_structured_with_events,1);assert.equal(result.metrics.valid_structured_empty,0);assert.equal(result.metrics.structured_events_created,1);assert.match(calls[0][0].content.find(item=>item.type==='text').text,/telemetry is a supporting signal only/i)})
test('Deep Vision message sends separate images in explicit chronological order',async()=>{const calls=[],result=await analyseDeepWindow({language:'en',interval:{id:'ordered',start:1,end:3},sequence:{frames:sequenceFrames},knownSubjects:['subject_1']},async messages=>{calls.push(messages);return '{"events":[]}' });const content=calls[0][0].content,labels=content.filter(item=>item.type==='text'&&/^Frame/.test(item.text)).map(item=>item.text);assert.equal(content.filter(item=>item.type==='image_url').length,3);assert.deepEqual(labels.map(label=>Number(label.match(/· ([\d.]+)s/)[1])),[1,2,3]);assert.equal(result.vision_window.visual_input.mode,'multi_image');assert.deepEqual(result.vision_window.visual_input.timestamps,[1,2,3])})
test('debug recorder exports raw parsed validated and visual input data for every VisionPsy window',async()=>{const result=await analyseDeepWindow({language:'en',interval:{id:'candidate_92',start:92.56,end:101.5,reasons:['object_interaction'],subjects:['subject_1'],salience:.99},sequence:{frames:sequenceFrames},knownSubjects:['subject_1']},async()=>'{"events":[{"actor_ref":"subject_1","action":"playing","confidence":0.84,"description":"The dog plays with a visible object."}]}' ),recorder=new DeepVideoDebugRecorder();recorder.recordVision(result);const window=recorder.toJSON().vision_windows[0];assert.equal(window.id,'candidate_92');assert.equal(window.start,92.56);assert.deepEqual(window.reasons,['object_interaction']);assert.equal(window.visual_input.mode,'multi_image');assert.match(window.raw_response,/"playing"/);assert.equal(window.parsed_response.events[0].action,'playing');assert.equal(window.validation_result.valid,true);assert.equal(window.validated_events[0].action,'playing');assert.deepEqual(window.validation_errors,[]);assert.equal(window.repair_attempted,false);assert.equal(window.schema_echo_detected,false);assert.equal(window.fallback_used,false)})
test('candidate generation adds coverage and keeps every review window bounded',()=>{const observations=Array.from({length:80},(_,index)=>({time:index*.2,subjects:index?[{subject_id:'subject_1',world_motion:{magnitude:.08}}]:[],events:[]})),windows=generateCandidateIntervals(observations,30,{coverageSeconds:10});assert.ok(windows.some(item=>item.reasons.includes('world_motion')));assert.ok(windows.some(item=>item.reasons.includes('temporal_coverage')));assert.ok(windows.every(item=>item.end-item.start<=10.001))} )
test('brief hand crossing for 0.3 seconds is interaction evidence but not petting',()=>{const tracker=new PersistentHandDogRelations(),events=[];for(const [index,x] of [.2,.5,.8].entries()){const signal=tracker.update({subjectId:'subject_1',time:index*.15,contact:true,handPoints:[[{x,y:.35}]],dogBox:[0,0,1,1]});if(signal.event)events.push(signal.event)}assert.deepEqual(events,[])})
test('repeated relative stroking over one second creates exactly one petting event',()=>{const tracker=new PersistentHandDogRelations(),events=[],positions=[.2,.27,.34,.27,.2,.27,.34];for(const [index,x] of positions.entries()){const signal=tracker.update({subjectId:'subject_1',time:index*.2,contact:true,handPoints:[[{x,y:.35}]],dogBox:[0,0,1,1]});if(signal.event)events.push(signal.event)}assert.equal(events.length,1);assert.equal(events[0].action,'petting');assert.ok(events[0].evidence.direction_changes>=2);assert.ok(events[0].evidence.relative_hand_travel>=.055)})
test('continuous stroking with tiny gaps stays one merged petting episode',()=>{const tracker=new PersistentHandDogRelations(),events=[],samples=[[0,.2],[.2,.27],[.4,.34],[.6,.27],[.8,.2],[1,.27],[1.2,null],[1.6,.34],[1.8,.27],[2,.2],[2.2,.27],[2.4,.34]];for(const [time,x] of samples){const signal=tracker.update({subjectId:'subject_1',time,contact:x!==null,handPoints:x===null?[]:[[{x,y:.35}]],dogBox:[0,0,1,1]});if(signal.event)events.push(signal.event)}assert.equal(events.length,1);const merged=mergePettingEpisodes([...events,{...events[0],id:'semantic_duplicate',start:2.6,end:3.1}],3.5);assert.equal(merged.filter(event=>event.action==='petting').length,1)})
test('persistent hand and unknown object geometry near the mouth promotes object review without petting',()=>{const hands=new PersistentHandDogRelations(),objects=new PersistentObjectInteractionEvidence(),observations=[],petting=[];for(let frame=0;frame<8;frame++){const time=frame*.2,mouth={x:.5,y:.3},hand={x:.54+(frame%2)*.005,y:.3},object=objects.update({subjectId:'subject_1',time,handPoint:hand,mouthPoint:mouth}),signal=hands.update({subjectId:'subject_1',time,contact:true,handPoints:[[hand]],dogBox:[.2,.15,.8,.8],objectEvidence:object.active});if(signal.event)petting.push(signal.event);observations.push({time,subjects:[],events:[],relations:[{type:'hand_dog_interaction',first:'subject_1',changed:true,persistent:signal.persistent,petting:false,object_interaction:object.active}],object_candidates:object.candidate?[object.candidate]:[]})}const candidates=generateCandidateIntervals(observations,2);assert.equal(petting.length,0);assert.ok(candidates.some(candidate=>candidate.reasons.includes('object_interaction')&&candidate.salience===.99&&/hand presenting an object/.test(candidate.semantic_hint)))})

test('story diversity caps eight petting candidates while preserving jumps and object actions',()=>{const petting=Array.from({length:8},(_,index)=>({id:`pet_${index}`,start:index*6,end:index*6+1,actor:index%2?'subject_2':'subject_1',action:'petting',confidence:.8,importance:.85,description:'A person pets the dog.'})),other=[{id:'off',start:50,end:51,actor:'subject_1',action:'jumping_off',confidence:.82,importance:.8,description:'The dog leaves the furniture.'},{id:'on',start:55,end:56,actor:'subject_1',action:'jumping_on',confidence:.82,importance:.8,description:'The dog returns to the furniture.'},{id:'play',start:60,end:63,actor:'subject_1',action:'playing',confidence:.84,importance:.9,description:'The dog plays with an object.'},{id:'hold',start:64,end:66,actor:'subject_1',action:'holding',confidence:.84,importance:.9,description:'The dog holds an object.'}],story=selectDeepV3StoryEvents([...petting,...other],{sessionDuration:70,maxEvents:8});assert.ok(story.filter(event=>event.action==='petting').length<=2);assert.ok(story.some(event=>event.action==='jumping_off'));assert.ok(story.some(event=>event.action==='jumping_on'));assert.ok(story.some(event=>event.action==='playing'));assert.ok(story.some(event=>event.action==='holding'))})
test('overlapping VisionPsy object behavior suppresses deterministic petting only in that interval',()=>{const events=[{id:'pet_overlap',start:92,end:95,actor:'subject_1',action:'petting',confidence:.78,importance:.92,description:'A person repeatedly strokes subject_1.',source:'relation-v3'},{id:'playing',start:93,end:98,actor:'subject_1',action:'playing',confidence:.84,importance:.92,description:'The dog plays with a visible object.',source:'visionpsy-v3'},{id:'pet_separate',start:70,end:73,actor:'subject_1',action:'petting',confidence:.8,importance:.9,description:'A person strokes subject_1.',source:'relation-v3'}],result=reconcileV3Events(events,{sessionDuration:101,maxEvents:12});assert.ok(result.events.some(event=>event.id==='playing'));assert.ok(result.events.some(event=>event.id==='pet_separate'));assert.equal(result.events.some(event=>event.id==='pet_overlap'),false);assert.ok(result.rejected.some(item=>item.event.id==='pet_overlap'&&item.reason==='overlapping_object_semantic_priority'))})
test('same-direction support transitions in one departure episode are deduplicated',()=>{const surface={surface:'furniture_surface',surface_id:'surface_1'},floor={surface:'floor',surface_id:null},events=[{id:'off_1',start:39.2,end:39.7,actor:'subject_1',action:'jumping_off',from:surface,to:floor,confidence:.78,description:'The dog leaves the furniture.',source:'surface-v3'},{id:'off_2',start:41.8,end:42.3,actor:'subject_1',action:'jumping_off',from:surface,to:floor,confidence:.82,description:'The dog leaves the furniture.',source:'surface-v3'},{id:'on',start:50,end:51,actor:'subject_1',action:'jumping_on',from:floor,to:surface,confidence:.84,description:'The dog returns.',source:'surface-v3'},{id:'off_later',start:60,end:61,actor:'subject_1',action:'jumping_off',from:surface,to:floor,confidence:.8,description:'The dog leaves again.',source:'surface-v3'}],result=reconcileV3Events(events,{sessionDuration:70,maxEvents:12}),off=result.events.filter(event=>event.action==='jumping_off');assert.equal(off.length,2);assert.equal(off[0].start,39.2);assert.equal(off[0].end,42.3);assert.ok(result.rejected.some(item=>item.event.id==='off_2'&&item.reason==='duplicate_support_episode'))})

test('surface telemetry is removed and semantic behavior dominates the final story',()=>{const fake=Array.from({length:6},(_,index)=>({id:`surface_${index}`,start:index*2,end:index*2+.5,actor:'subject_1',action:'scene_change',confidence:.9,importance:.9,description:'Furniture label changed.',source:'surface-v3',from:{surface:index%2?'bed':'couch',surface_id:'surface_1'},to:{surface:index%2?'chair':'bed',surface_id:'surface_1'}})),semantic=[{id:'pet_1',start:14,end:18,actor:'subject_1',action:'petting',confidence:.84,importance:.9,description:'A person pets subject_1.'},{id:'off',start:38,end:40,actor:'subject_1',action:'jumping_off',confidence:.8,importance:.7,description:'subject_1 moves to the floor.',source:'surface-v3',from:{surface:'furniture_surface',surface_id:'surface_1'},to:{surface:'floor',surface_id:null}},{id:'on',start:49,end:52,actor:'subject_1',action:'jumping_on',confidence:.8,importance:.7,description:'subject_1 returns to the furniture.',source:'surface-v3',from:{surface:'floor',surface_id:null},to:{surface:'furniture_surface',surface_id:'surface_1'}},{id:'pet_2',start:66,end:69,actor:'subject_2',action:'petting',confidence:.86,importance:.9,description:'A person pets subject_2.'},{id:'play',start:94,end:97,actor:'subject_1',action:'playing',confidence:.84,importance:.9,description:'subject_1 plays with a toy.'}],reconciled=reconcileV3Events([...fake,...semantic],{sessionDuration:100,maxEvents:12}),story=selectDeepV3StoryEvents(reconciled.events,{sessionDuration:100,maxEvents:12});assert.equal(reconciled.events.some(event=>event.action==='scene_change'),false);assert.equal(story.filter(event=>['jumping_on','jumping_off'].includes(event.action)).length,2);assert.ok(story.filter(event=>['petting','playing'].includes(event.action)).length>=3);assert.ok(story.length<=5)})

test('schema or JSON model data can never become the final narrative',()=>{const events=[{id:'safe',start:1,end:2,actor:'subject_1',action:'petting',confidence:.9,description:'A person pets the dog.'}],summary=sanitizeFinalNarrative(schemaEchoRegression,events,'en');assert.equal(hasNarrativeSchemaContamination(schemaEchoRegression),true);assert.equal(hasNarrativeSchemaContamination(summary),false);assert.match(summary,/person pets the dog/i);assert.doesNotMatch(summary,/actor_ref|"action"\s*:|\{\s*"?events|\|/)})

test('summary modal CSS is viewport-fixed, scrollable and keeps actions reachable',()=>{const css=fs.readFileSync(path.resolve(here,'../public/styles.css'),'utf8');assert.match(css,/\.session-modal\s*\{[^}]*position:fixed[^}]*left:0[^}]*top:0[^}]*width:100vw[^}]*height:100dvh[^}]*overflow-y:auto/s);assert.match(css,/\.session-modal section\s*\{[^}]*max-width:540px[^}]*max-height:calc\(100dvh - 32px\)[^}]*overflow-y:auto/s);assert.match(css,/\.summary-actions\s*\{[^}]*position:sticky[^}]*bottom:-1px/s)})

test('golden regression evaluator enforces six of seven groups and forbidden events',()=>{const actual=[
  {id:'1',start:14,end:18,actor:'subject_1',action:'petting',confidence:.9,description:'petted'},
  {id:'2',start:38,end:40,actor:'subject_1',action:'jumping_off',confidence:.9,description:'jumps off'},
  {id:'3',start:41,end:44,actor:'subject_1',action:'person_dog_interaction',confidence:.8,description:'interacts'},
  {id:'4',start:49,end:52,actor:'subject_1',action:'jumping_on',confidence:.9,description:'jumps on'},
  {id:'5',start:66,end:69,actor:'subject_2',action:'petting',confidence:.9,description:'petted'},
  {id:'6',start:89,end:93,actor:'subject_1',action:'mouth_contact',confidence:.85,description:'grabs toy'},
  {id:'7',start:94,end:97,actor:'subject_1',action:'playing',confidence:.85,description:'plays'}
],metrics=evaluateRegressionV001(actual,fixture);assert.equal(metrics.required_matched,7);assert.equal(metrics.persistent_dog_identities,2);assert.equal(metrics.false_bed_transitions,0);assert.equal(metrics.camera_motion_story_events,0);assert.equal(metrics.pass,true)})
