import test from 'node:test'
import assert from 'node:assert/strict'
import fs from 'node:fs'
import path from 'node:path'
import {fileURLToPath} from 'node:url'
import {
  estimateGlobalTranslation,compensateSubjectMotionV3,PersistentSurfaceMap,PersistentIdentityManager,
  PersistentHandDogRelations,TemporalPostureClassifier,parseVisionStructuredPayload,validateStructuredVision,
  conservativeVisionFallback,generateCandidateIntervals,reconcileV3Events,selectDeepV3StoryEvents,evaluateRegressionV001
} from '../public/deep-video-v3.js'
import {analyseDeepWindow,hasNarrativeSchemaContamination,sanitizeFinalNarrative} from '../studio.mjs'

const here=path.dirname(fileURLToPath(import.meta.url))
const fixture=JSON.parse(fs.readFileSync(path.resolve(here,'../../tests/fixtures/regression-video-001.expected.json'),'utf8'))
const schemaEchoRegression='In the video, [ { "events": [ { "actor_ref": "subject_1", "action": "petting|lying_down|standing_up|sitting_down|jumping_off|jumping_on|approaching_person|rear_up|tail_wagging|sniffing|object_presented|mouth_contact|picking_up|holding|carrying|playing|tugging|dropping|dog_dog_interaction|person_dog_interaction|resting|walking|running|rolling|other"'

function texture(width=80,height=80){const data=new Uint8Array(width*height);for(let y=0;y<height;y++)for(let x=0;x<width;x++)data[y*width+x]=(x*17+y*29+(x*y)%97)%256;return data}
function shifted(input,dx,dy,width=80,height=80){const output=new Uint8Array(input.length);for(let y=0;y<height;y++)for(let x=0;x<width;x++){const px=x-dx,py=y-dy;output[y*width+x]=px>=0&&px<width&&py>=0&&py<height?input[py*width+px]:0}return output}
const descriptor=(hue=0)=>({histogram:Array.from({length:20},(_,index)=>index===hue?1:0),shape:[.4,.3,.2,.2]})

test('camera pan is recovered from multiple static background features',()=>{const previous=texture(),current=shifted(previous,4,-3),motion=estimateGlobalTranslation(previous,current,{width:80,height:80,maxShift:7});assert.ok(Math.abs(motion.dx-.05)<.014);assert.ok(Math.abs(motion.dy+.0375)<.014);assert.ok(motion.inliers>100);assert.ok(motion.confidence>.25)})
test('static dog with moving camera has near-zero residual motion',()=>{const residual=compensateSubjectMotionV3({dx:.05,dy:-.02},{dx:.05,dy:-.02,confidence:.8});assert.ok(residual.magnitude<1e-6)})
test('moving dog with static camera retains subject motion',()=>{const residual=compensateSubjectMotionV3({dx:.06,dy:0},{dx:0,dy:0,confidence:.8});assert.ok(Math.abs(residual.dx-.06)<1e-6)})
test('camera and dog moving together preserve only residual movement',()=>{const residual=compensateSubjectMotionV3({dx:.08,dy:.01},{dx:.05,dy:.01,confidence:.8});assert.ok(Math.abs(residual.dx-.03)<1e-6)})

test('alternating couch bed couch chair bed labels stay one generic surface with no transition',()=>{const map=new PersistentSurfaceMap({confirmFrames:3,relationFrames:2}),dog={subject_id:'subject_1',box:[.25,.28,.55,.62]},transitions=[],labels=['couch','bed','couch','chair','bed'];for(let frame=0;frame<40;frame++){map.updateDetections([{label:labels[frame%labels.length],score:.8,box:[.18,.2,.72,.72]}],frame*.2);const transition=map.updateRelation(dog,frame*.2);if(transition)transitions.push(transition)}const surfaces=map.snapshot();assert.equal(surfaces.length,1);assert.equal(surfaces[0].stable_type,'furniture_surface');assert.equal(transitions.length,0);assert.equal(JSON.stringify(transitions).includes('bed'),false)})
test('leaving and returning to persistent furniture creates only cooled geometric support events',()=>{const map=new PersistentSurfaceMap({confirmFrames:2,relationFrames:2,cooldownSeconds:1}),on={subject_id:'subject_1',box:[.25,.28,.55,.62]},floor={subject_id:'subject_1',box:[.76,.45,.96,.9]};for(let frame=0;frame<4;frame++){map.updateDetections([{label:'couch',score:.9,box:[.18,.2,.72,.72]}],frame*.2);map.updateRelation(on,frame*.2)}let off=null;for(let frame=4;frame<7;frame++)off=map.updateRelation(floor,frame*.2)||off;assert.equal(off.action,'jumping_off');let back=null;for(let frame=13;frame<16;frame++)back=map.updateRelation(on,frame*.2)||back;assert.equal(back.action,'jumping_on');assert.equal(off.to.surface,'floor');assert.equal(back.from.surface,'floor')})
test('moving between furniture entities never creates a semantic scene change',()=>{const map=new PersistentSurfaceMap({confirmFrames:2,relationFrames:2,cooldownSeconds:0}),left={subject_id:'subject_1',box:[.12,.25,.34,.62]},right={subject_id:'subject_1',box:[.66,.25,.88,.62]},detections=[{label:'couch',score:.9,box:[.06,.18,.42,.72]},{label:'chair',score:.9,box:[.58,.18,.95,.72]}],events=[];for(let frame=0;frame<4;frame++){map.updateDetections(detections,frame*.2);map.updateRelation(left,frame*.2)}for(let frame=4;frame<8;frame++){map.updateDetections(detections,frame*.2);const event=map.updateRelation(right,frame*.2);if(event)events.push(event)}assert.equal(map.entities.size,2);assert.deepEqual(events,[])})

test('lost dog with a new temporary track revives the persistent subject',()=>{const manager=new PersistentIdentityManager({newSubjectFrames:2,newSubjectSeconds:10,matchThreshold:.4}),box=[.2,.2,.5,.7];manager.update([{label:'dog',track_id:'track_1',box,descriptor:descriptor(2)}],0);const created=manager.update([{label:'dog',track_id:'track_1',box,descriptor:descriptor(2)}],.2)[0];assert.equal(created.subject_id,'subject_1');const revived=manager.update([{label:'dog',track_id:'track_9',box:[.22,.2,.52,.7],descriptor:descriptor(2)}],2)[0];assert.equal(revived.subject_id,'subject_1');assert.equal(revived.identity_decision,'revived');assert.equal(manager.subjects.size,1)})

test('temporal posture classifier implements stable sitting',()=>{const points=Array.from({length:17},()=>({x:0,y:0,score:0}));points[3]={x:.4,y:.3,score:.9};points[4]={x:.6,y:.65,score:.9};for(const index of [7,10])points[index]={x:.42,y:.85,score:.85};for(const index of [13,16])points[index]={x:.62,y:.72,score:.85};const classifier=new TemporalPostureClassifier({confirmFrames:2,minConfidence:.5});classifier.update('subject_1',points,0);const stable=classifier.update('subject_1',points,.3);assert.equal(stable.stable,'sitting')})

test('malformed structured response is explicit and useful fallback is retained',()=>{const invalid=validateStructuredVision('The dog is tail wagging and is being petted.',{interval:{start:2,end:5},knownSubjects:['subject_1']});assert.equal(invalid.valid,false);assert.ok(invalid.errors.includes('invalid_json_or_schema'));const fallback=conservativeVisionFallback('The dog is tail wagging and is being petted.',{interval:{start:2,end:5},actor:'subject_1'});assert.deepEqual(new Set(fallback.map(event=>event.action)),new Set(['tail_wagging','petting']))})
test('exact Regression 001 schema echo produces zero fallback or semantic events',async()=>{assert.equal(conservativeVisionFallback(schemaEchoRegression,{interval:{start:0,end:3},actor:'subject_1'}).length,0);const calls=[];const result=await analyseDeepWindow({language:'en',interval:{start:0,end:3},sequence:{image:'data:image/jpeg;base64,AA=='},knownSubjects:['subject_1']},async messages=>{calls.push(messages);return schemaEchoRegression});const prompt=calls[0][0].content.find(item=>item.type==='text').text;assert.equal(calls.length,1);assert.doesNotMatch(prompt,/petting\s*\|\s*lying_down/);assert.match(prompt,/"actor_ref":"subject_1","action":"petting"/);assert.doesNotMatch(prompt,/surface_before|evidence|object_label/);assert.equal(result.events.length,0);assert.ok(result.decisions.some(item=>item.reason==='schema_echo_or_template'))})
test('a copied JSON action template is rejected before event construction',()=>{const copied=JSON.stringify({events:[{actor_ref:'subject_1',action:'petting|lying_down|standing_up|holding|playing',start:0,end:1,confidence:.9,evidence:['short observable reason']}],context:{environment:'unknown'}}),validated=validateStructuredVision(copied,{interval:{start:0,end:2},knownSubjects:['subject_1']});assert.equal(validated.valid,false);assert.equal(validated.events.length,0);assert.ok(validated.errors.includes('schema_echo_or_template'))})
test('valid structured response produces persistent-reference events',()=>{const parsed=validateStructuredVision(JSON.stringify({events:[{actor_ref:'subject_1',action:'petting',target_ref:'person_1',start:3,end:5,confidence:.86,evidence:['hand repeatedly contacts the dog']}],context:{environment:'indoor',scene:'home'}}),{interval:{start:2,end:6},knownSubjects:['subject_1','person_1']});assert.equal(parsed.valid,true);assert.equal(parsed.events.length,1);assert.equal(parsed.events[0].actor,'subject_1')})
test('Vision parser accepts wrapped, array, single-object and repairable almost-JSON forms',()=>{const interval={start:4,end:7},knownSubjects=['subject_1','person_1'],cases=[
  'Here is the result: {"events":[{"actor_ref":"subject_1","action":"petting","confidence":0.8}]} Thanks.',
  '[{"actor_ref":"subject_1","action":"playing","confidence":0.75}]',
  '{"actor_ref":"subject_1","action":"tail-wagging","confidence":0.72}',
  '```json\n{"events":[{"actor":"subject_1","action":"petting","detail":"A hand strokes the dog.","confidence":0.8},],}\n```',
  "{'events':[{'subject':'subject_1','action':'playing','target':'person_1','confidence':0.7}]}",
  '“actor”: “subject_1”, “action”: “petting”'
];for(const value of cases){const wrapped=value.startsWith('“')?`{${value}}`:value,parsed=validateStructuredVision(wrapped,{interval,knownSubjects});assert.equal(parsed.valid,true,value);assert.equal(parsed.events.length,1,value);assert.equal(parsed.events[0].start,4);assert.equal(parsed.events[0].end,7);assert.ok(parsed.events[0].description.length>8)}})
test('normal action gets conservative default confidence but high-specificity action does not',()=>{const normal=validateStructuredVision({actor:'subject_1',action:'playing'},{interval:{start:1,end:2},knownSubjects:['subject_1']}),specific=validateStructuredVision({actor:'subject_1',action:'biting'},{interval:{start:1,end:2},knownSubjects:['subject_1']});assert.equal(normal.events[0].confidence,.68);assert.equal(specific.events.length,0)})
test('malformed VisionPsy JSON is retried once and repaired',async()=>{const replies=['not valid json but the dog is being petted',JSON.stringify({events:[{actor_ref:'subject_1',action:'petting',target_ref:'person_1',start:3,end:5,confidence:.86,evidence:['repeated hand contact']}],context:{environment:'indoor',scene:'home'}})],calls=[];const result=await analyseDeepWindow({language:'en',interval:{start:2,end:6},sequence:{image:'data:image/jpeg;base64,AA=='},knownSubjects:['subject_1','person_1']},async messages=>{calls.push(messages);return replies.shift()});assert.equal(calls.length,2);assert.equal(result.metrics.repaired_responses,1);assert.equal(result.events.length,1);assert.ok(result.decisions.some(item=>item.status==='accepted'))})
test('candidate generation adds coverage and keeps every review window bounded',()=>{const observations=Array.from({length:80},(_,index)=>({time:index*.2,subjects:index?[{subject_id:'subject_1',world_motion:{magnitude:.08}}]:[],events:[]})),windows=generateCandidateIntervals(observations,30,{coverageSeconds:10});assert.ok(windows.some(item=>item.reasons.includes('world_motion')));assert.ok(windows.some(item=>item.reasons.includes('temporal_coverage')));assert.ok(windows.every(item=>item.end-item.start<=10.001))} )
test('persistent moving hand contact creates petting evidence and a high-salience candidate',()=>{const tracker=new PersistentHandDogRelations({confirmFrames:3,confirmSeconds:.3,minTravel:.005,cooldownSeconds:2}),observations=[];let petting=null;for(let frame=0;frame<5;frame++){const time=frame*.2,signal=tracker.update({subjectId:'subject_1',time,contact:true,handPoints:[[{x:.3+frame*.01,y:.3}]]});petting=signal.event||petting;observations.push({time,subjects:[],events:signal.event?[signal.event]:[],relations:[{type:'hand_dog',first:'subject_1',changed:true,persistent:signal.active}]})}assert.equal(petting.action,'petting');const candidates=generateCandidateIntervals(observations,1);assert.ok(candidates.some(candidate=>candidate.reasons.includes('petting_signal')&&candidate.salience===.98))})

test('surface telemetry is removed and semantic behavior dominates the final story',()=>{const fake=Array.from({length:6},(_,index)=>({id:`surface_${index}`,start:index*2,end:index*2+.5,actor:'subject_1',action:'scene_change',confidence:.9,importance:.9,description:'Furniture label changed.',source:'surface-v3',from:{surface:index%2?'bed':'couch',surface_id:'surface_1'},to:{surface:index%2?'chair':'bed',surface_id:'surface_1'}})),semantic=[{id:'pet_1',start:14,end:18,actor:'subject_1',action:'petting',confidence:.84,importance:.9,description:'A person pets subject_1.'},{id:'off',start:38,end:40,actor:'subject_1',action:'jumping_off',confidence:.8,importance:.7,description:'subject_1 moves to the floor.',source:'surface-v3',from:{surface:'furniture_surface',surface_id:'surface_1'},to:{surface:'floor',surface_id:null}},{id:'on',start:49,end:52,actor:'subject_1',action:'jumping_on',confidence:.8,importance:.7,description:'subject_1 returns to the furniture.',source:'surface-v3',from:{surface:'floor',surface_id:null},to:{surface:'furniture_surface',surface_id:'surface_1'}},{id:'pet_2',start:66,end:69,actor:'subject_2',action:'petting',confidence:.86,importance:.9,description:'A person pets subject_2.'},{id:'play',start:94,end:97,actor:'subject_1',action:'playing',confidence:.84,importance:.9,description:'subject_1 plays with a toy.'}],reconciled=reconcileV3Events([...fake,...semantic],{sessionDuration:100,maxEvents:12}),story=selectDeepV3StoryEvents(reconciled.events,{sessionDuration:100,maxEvents:12});assert.equal(reconciled.events.some(event=>event.action==='scene_change'),false);assert.equal(story.filter(event=>['jumping_on','jumping_off'].includes(event.action)).length,2);assert.ok(story.filter(event=>['petting','playing'].includes(event.action)).length>=3);assert.ok(story.length<=5)})

test('schema or JSON model data can never become the final narrative',()=>{const events=[{id:'safe',start:1,end:2,actor:'subject_1',action:'petting',confidence:.9,description:'A person pets the dog.'}],summary=sanitizeFinalNarrative(schemaEchoRegression,events,'en');assert.equal(hasNarrativeSchemaContamination(schemaEchoRegression),true);assert.equal(hasNarrativeSchemaContamination(summary),false);assert.match(summary,/person pets the dog/i);assert.doesNotMatch(summary,/actor_ref|"action"\s*:|\{\s*"?events|\|/)})

test('summary modal CSS is viewport-fixed, scrollable and keeps actions reachable',()=>{const css=fs.readFileSync(path.resolve(here,'../public/styles.css'),'utf8');assert.match(css,/\.session-modal\s*\{[^}]*position:fixed[^}]*left:0[^}]*top:0[^}]*width:100vw[^}]*height:100dvh[^}]*overflow-y:auto/s);assert.match(css,/\.session-modal section\s*\{[^}]*max-width:540px[^}]*max-height:calc\(100dvh - 32px\)[^}]*overflow-y:auto/s);assert.match(css,/\.summary-actions\s*\{[^}]*position:sticky[^}]*bottom:-1px/s)})

test('golden regression evaluator enforces six of seven groups and forbidden events',()=>{const actual=[
  {id:'1',start:14,end:18,actor:'subject_1',action:'petting',confidence:.9,description:'petted'},
  {id:'2',start:38,end:40,actor:'subject_1',action:'jumping_off',confidence:.9,description:'jumps off'},
  {id:'3',start:41,end:44,actor:'subject_1',action:'person_dog_interaction',confidence:.8,description:'interacts'},
  {id:'4',start:49,end:52,actor:'subject_1',action:'jumping_on',confidence:.9,description:'jumps on'},
  {id:'5',start:66,end:69,actor:'subject_2',action:'petting',confidence:.9,description:'petted'},
  {id:'6',start:89,end:93,actor:'subject_1',action:'mouth_contact',confidence:.85,description:'grabs toy'},
  {id:'7',start:94,end:97,actor:'subject_1',action:'playing',confidence:.85,description:'plays'}
],metrics=evaluateRegressionV001(actual,fixture);assert.equal(metrics.required_matched,7);assert.equal(metrics.persistent_dog_identities,2);assert.equal(metrics.false_bed_transitions,0);assert.equal(metrics.camera_motion_story_events,0);assert.equal(metrics.pass,true)})
